### ISSUE TITLE
when I want to type past the first time the first letter is not inputed

### ISSUE THREAD

**Issue by zenitogr** [PR4S4D/groq-cli#1]
leading to having to type one char and then type my text

windows 11
just installed go
followed the instructions to build and run (and env setting)
even re cloned the github repo and run the groq-cli.exe provided in the repo

same issue

**Comment by zenitogr** [comment]
tested with cmd also the same

first time with powershell

both times in windows termninal

**Comment by PR4S4D** [comment]
Hello @zenitogr, 
Thank you for reporting the issue.
Even I am using windows 11 and windows terminal. However, I am not facing any issue with the first character :/
 
https://github.com/PR4S4D/groq-cli/assets/20255076/07945c27-4f88-4bf6-a46e-555f9d4295d4

Could you share a short video please? 
Regards!

**Comment by zenitogr** [comment]
https://github.com/PR4S4D/groq-cli/assets/109196423/75317595-dde7-42b7-af88-aaeb8f6d76d6

here as you see I type two times hello and the second time it eats the h

can you tell me how to debug this? like is there a log somewhere?

**Comment by zenitogr** [comment]
I used wsl with ubuntu 22.04 LTS and install golang-go and followed the instructions and it works correctly. something with my windows install and powershell/cmd/terminal also installed latest powershell same issue

**Comment by zenitogr** [comment]
also set default powershell without terminal and still the same bug so its not terminal as it works with wsl and it doesnt work without terminal with powershell standalone

**Comment by zenitogr** [comment]
ok it runs correctly on the integrated powershell in vs code
I guess something is up with my windows installation and powershell/cmd

you can close this as it must be a local problem with my powershell/cmd

**Comment by PR4S4D** [comment]
I tried on multiple shells and on two different PCs. It seems to be okay for me.
I am using https://github.com/charmbracelet/huh?tab=readme-ov-file#input for the input field.

Thank you for your time on this issue :)
